### ISSUE TITLE
Cannot open large pools

### ISSUE THREAD

**Issue by RobDickinson** [pmem/pmemkv-java#9]
1GB pools work fine, but 2GB and higher fail to open.

```
robfromboulder@radware-ubuntu:~/work/pmemkv-tools$ make java_bench
rm -rf /dev/shm/pmemkv /tmp/pmemkv
rm -rf ./java/*.class
cd java
javac -cp ../../pmemkv-java/target/*.jar Bench.java
PMEM_IS_PMEM_FORCE=1 java -cp .:`find ../../pmemkv-java/target -name *.jar` -Djava.library.path=/usr/local/lib Bench

Testing kvtree2 engine...
[kvengine] -2147483648
Exception in thread "main" java.lang.IllegalArgumentException: unable to open persistent pool
	at io.pmem.pmemkv.KVEngine.kvengine_open(Native Method)
	at io.pmem.pmemkv.KVEngine.<init>(KVEngine.java:42)
	at Bench.test_engine(Bench.java:7)
	at Bench.main(Bench.java:55)
Makefile:10: recipe for target 'java_bench' failed
make: *** [java_bench] Error 1
```

This issue only appears to affect the Java bindings -- I could open large pools using `pmemkv_bench` Ruby bindings, so it's probably not an issue with core pmemkv.

**Comment by RobDickinson** [comment]
What's happening is Java interprets expressions as integers unless otherwise indicated, and this was causing an integer overflow with large values.  The proper way is to make sure at least one operand in the expression is explicitly a long.  `2 * 1024 * 1024 * 1024L`
